local Test = dofile("tests/assert.lua")
local loadAddonFile = dofile("tests/load_module.lua")
local addon = {}
loadAddonFile("Markdown.lua", addon)
loadAddonFile("Storage.lua", addon)
loadAddonFile("Renderer.lua", addon)
loadAddonFile("Overlay.lua", addon)
loadAddonFile("Commands.lua", addon)
dofile("tests/markdown_test.lua")(addon, Test)
dofile("tests/storage_test.lua")(addon, Test)
dofile("tests/renderer_test.lua")(addon, Test)
dofile("tests/editor_test.lua")(addon, Test)
dofile("tests/overlay_test.lua")(addon, Test)
dofile("tests/commands_test.lua")(addon, Test)

Test.run("test harness", function()
    Test.equal("arithmetic", 2 + 2, 4)
end)

print("All tests passed")
